import { Category, Website } from '@/types';

export const categories: Category[] = [
  {
    id: '1',
    name: 'Rules',
    slug: 'rules',
    description: 'Cursor Rules and Guides',
    order: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '2',
    name: 'MCP',
    slug: 'mcp',
    description: 'Multi-modal Control Protocol Resources',
    order: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '3',
    name: 'Website Building',
    slug: 'website-building',
    description: 'Website Development Resources',
    order: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '4',
    name: 'App Development',
    slug: 'app-development',
    description: 'App Development Resources',
    order: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '5',
    name: 'AI Tools',
    slug: 'ai-tools',
    description: 'AI Development Tools',
    order: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const websites: Website[] = [
  {
    id: '1',
    name: 'Cursor Official',
    url: 'https://cursor.sh',
    description: 'The official website for Cursor, the AI-first code editor',
    icon: '/icons/cursor.svg',
    categoryId: '1',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '2',
    name: 'Cursor Documentation',
    url: 'https://cursor.sh/docs',
    description: 'Official documentation for Cursor editor',
    icon: '/icons/cursor-docs.svg',
    categoryId: '1',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '3',
    name: 'MCP GitHub',
    url: 'https://github.com/cursor-ai-inc/mcp-standard',
    description: 'Multi-modal Control Protocol GitHub Repository',
    icon: '/icons/github.svg',
    categoryId: '2',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '4',
    name: 'MCP Documentation',
    url: 'https://mcp-standard.cursor.sh/',
    description: 'Official MCP documentation',
    icon: '/icons/mcp.svg',
    categoryId: '2',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '5',
    name: 'Next.js',
    url: 'https://nextjs.org',
    description: 'The React framework for the web',
    icon: '/icons/nextjs.svg',
    categoryId: '3',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '6',
    name: 'Vercel',
    url: 'https://vercel.com',
    description: 'Deploy web projects with the best frontend experience',
    icon: '/icons/vercel.svg',
    categoryId: '3',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '7',
    name: 'React Native',
    url: 'https://reactnative.dev',
    description: 'Create native apps for Android and iOS using React',
    icon: '/icons/react-native.svg',
    categoryId: '4',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '8',
    name: 'Flutter',
    url: 'https://flutter.dev',
    description: 'Google\'s UI toolkit for building beautiful apps',
    icon: '/icons/flutter.svg',
    categoryId: '4',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '9',
    name: 'Hugging Face',
    url: 'https://huggingface.co',
    description: 'The AI community building the future',
    icon: '/icons/huggingface.svg',
    categoryId: '5',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '10',
    name: 'Anthropic Claude',
    url: 'https://www.anthropic.com/claude',
    description: 'Constitutional AI assistant by Anthropic',
    icon: '/icons/anthropic.svg',
    categoryId: '5',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const getCategoriesWithWebsites = () => {
  return categories.map(category => ({
    ...category,
    websites: websites.filter(website => website.categoryId === category.id),
  }));
}; 